#! /bin/bash

# Usage: ./form <robot no.1> <robot no.2> ... <robot no.N> [-c <args for ./deploy>]
# Produces: formation.conf file to be read by other scripts, formation.txt file for humans

FORM_FILE="formation.conf"
# FORM_HUMAN_FILE="formation.txt"
FORM_BAK_FILE="formation.conf.BAK"

if [ -f "$FORM_FILE" ]
then
    if [ -f "$FORM_BAK_FILE" ]
    then
        rm $FORM_BAK_FILE
    fi
    mv $FORM_FILE $FORM_BAK_FILE
fi
touch $FORM_FILE

# if [ -f "$FORM_HUMAN_FILE" ]
# then
#     rm $FORM_HUMAN_FILE
# fi
# touch $FORM_HUMAN_FILE

number=1
address_prefix=""
copyfiles_mode=""
# for arg in "$@"; do
while true ; do
    # case $arg in
    case $1 in
        "")
            break
            ;;
        16 | Augusto | Alice | A | P |Tower)
            echo "Augusto is no. $number"
            # echo "$number 16" >> $FORM_FILE
            # echo "$number 16 Augusto" >> $FORM_HUMAN_FILE
            echo "$number 16 Augusto" >> $FORM_FILE
            (( number += 1 ))
            ;;
        17 | Caligola | Bob | B | Q | Star)
            echo "Caligola is no. $number"
            # echo "$number 17" >> $FORM_FILE
            # echo "$number 17 Caligola" >> $FORM_HUMAN_FILE
            echo "$number 17 Caligola" >> $FORM_FILE
            (( number += 1 ))
            ;;
        18 | Cesare | Carol | C | R | Moon)
            echo "Cesare is no. $number"
            # echo "$number 18" >> $FORM_FILE
            # echo "$number 18 Cesare" >> $FORM_HUMAN_FILE
            echo "$number 18 Cesare" >> $FORM_FILE
            (( number += 1 ))
            ;;
        19 | Claudio | David | D | S | Sun)
            echo "Claudio is no. $number"
            # echo "$number 19" >> $FORM_FILE
            # echo "$number 19 Claudio" >> $FORM_HUMAN_FILE
            echo "$number 19 Claudio" >> $FORM_FILE
            (( number += 1 ))
            ;;
        20 | Nerone | Eve | E | T | Judgement)
            echo "Nerone is no. $number"
            # echo "$number 20" >> $FORM_FILE
            # echo "$number 20 Nerone" >> $FORM_HUMAN_FILE
            echo "$number 20 Nerone" >> $FORM_FILE
            (( number += 1 ))
            ;;
        21 | Tiberio | Frank | F | U | World)
            echo "Tiberio is no. $number"
            # echo "$number 21" >> $FORM_FILE
            # echo "$number 21 Tiberio" >> $FORM_HUMAN_FILE
            echo "$number 21 Tiberio" >> $FORM_FILE
            (( number += 1 ))
            ;;
        -c | --copyfiles | -d | --deploy)
            shift
            # echo "Now I'd do deploy with these extra parameters: $@"
            ./deploy $@
            break
            ;;
    esac
    shift

done

# if [ $do_copyfiles -eq 1 ]
# then
#     echo "You asked to do copyfiles"
# fi
